services:
  - type: web
    name: edge-tts-server
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.3
    healthCheckPath: /health
